"""initial schema

Revision ID: 124c7caa60d6
Revises: 
Create Date: 2026-09-23 16:43:00.497078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '124c7caa60d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('native_currency', sa.String(length=50), nullable=False),
    sa.Column('explorer_api_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockchains_name'), 'blockchains', ['name'], unique=True)
    op.create_index(op.f('ix_blockchains_symbol'), 'blockchains', ['symbol'], unique=True)
    op.create_table('time_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('hour', 'day', 'week', name='timeunitname', native_enum=False, length=10), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_units_name'), 'time_units', ['name'], unique=True)
    op.create_table('fee_chart_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blockchain_id', sa.Integer(), nullable=False),
    sa.Column('time_unit_id', sa.Integer(), nullable=False),
    sa.Column('fee_value', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blockchain_id'], ['blockchains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_unit_id'], ['time_units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_chart_data_blockchain_id'), 'fee_chart_data', ['blockchain_id'], unique=False)
    op.create_index('ix_fee_chart_data_point', 'fee_chart_data', ['blockchain_id', 'time_unit_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_fee_chart_data_recorded_at'), 'fee_chart_data', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_fee_chart_data_time_unit_id'), 'fee_chart_data', ['time_unit_id'], unique=False)
    op.create_table('fee_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blockchain_id', sa.Integer(), nullable=False),
    sa.Column('time_unit_id', sa.Integer(), nullable=False),
    sa.Column('raw_fee_value', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('usd_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('avg_fee', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('median_fee', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('min_fee', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('max_fee', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('previous_value', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('status', sa.Enum('up', 'down', 'stable', name='feestatus', native_enum=False, length=10), nullable=False),
    sa.Column('change_percentage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blockchain_id'], ['blockchains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_unit_id'], ['time_units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_snapshots_blockchain_id'), 'fee_snapshots', ['blockchain_id'], unique=False)
    op.create_index(op.f('ix_fee_snapshots_recorded_at'), 'fee_snapshots', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_fee_snapshots_time_unit_id'), 'fee_snapshots', ['time_unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fee_snapshots_time_unit_id'), table_name='fee_snapshots')
    op.drop_index(op.f('ix_fee_snapshots_recorded_at'), table_name='fee_snapshots')
    op.drop_index(op.f('ix_fee_snapshots_blockchain_id'), table_name='fee_snapshots')
    op.drop_table('fee_snapshots')
    op.drop_index(op.f('ix_fee_chart_data_time_unit_id'), table_name='fee_chart_data')
    op.drop_index(op.f('ix_fee_chart_data_recorded_at'), table_name='fee_chart_data')
    op.drop_index('ix_fee_chart_data_point', table_name='fee_chart_data')
    op.drop_index(op.f('ix_fee_chart_data_blockchain_id'), table_name='fee_chart_data')
    op.drop_table('fee_chart_data')
    op.drop_index(op.f('ix_time_units_name'), table_name='time_units')
    op.drop_table('time_units')
    op.drop_index(op.f('ix_blockchains_symbol'), table_name='blockchains')
    op.drop_index(op.f('ix_blockchains_name'), table_name='blockchains')
    op.drop_table('blockchains')
    # ### end Alembic commands ###
